LANGUAGES = {
    'zh': {
        'name': 'Chinese, Mandarin (Simplified, China)',
        'code': 'zh',
        'punctuation': True,
        'language': 'zh',
    },
    'zh-TW': {
        'name': 'Chinese, Mandarin (Traditional, Taiwan)',
        'code': 'zh-TW',
        'punctuation': True,
        'language': 'zh-Hant',
    },
    'cs-CZ': {
        'name': 'Czech (Czech Replublic)',
        'code': 'cs-CZ',
        'punctuation': True,
        'language': 'cs',
    },
    'en-AU': {
        'name': 'English (Australia)',
        'code': 'en-AU',
        'punctuation': True,
        'language': 'en',
    },
    'en-IN': {
        'name': 'English (India)',
        'code': 'en-IN',
        'punctuation': True,
        'language': 'en',
    },
    'en-SG': {
        'name': 'English (Singapore)',
        'code': 'en-SG',
        'punctuation': True,
        'language': 'en',
    },
    'en-GB': {
        'name': 'English (United Kingdom)',
        'code': 'en-GB',
        'punctuation': True,
        'language': 'en',
    },
    'en-US': {
        'name': 'English (United States)',
        'code': 'en-US',
        'punctuation': True,
        'language': 'en',
    },
    'fr-FR': {
        'name': 'French (France)',
        'code': 'fr-FR',
        'punctuation': True,
        'language': 'fr',
    },
    'de-DE': {
        'name': 'German (Germany)',
        'code': 'de-DE',
        'punctuation': True,
        'language': 'de',
    },
    'it-IT': {
        'name': 'Italian (Italy)',
        'code': 'it-IT',
        'punctuation': True,
        'language': 'it',
    },
    'ja-JP': {
        'name': 'Japanese (Japan)',
        'code': 'ja-JP',
        'punctuation': True,
        'language': 'ja',
    },
    'ko-KR': {
        'name': 'Korean (South Korea)',
        'code': 'ko-KR',
        'punctuation': True,
        'language': 'ko',
    },
    'es-US': {
        'name': 'Spanish (United States)',
        'code': 'es-US',
        'punctuation': True,
        'language': 'es',
    },
}
