substitutions:
  _NODE_VERSION: "14.16.0"

steps:
  - name: "node:${_NODE_VERSION}-buster-slim"
    dir: "web"
    entrypoint: "npm"
    args: ["install"]
  - name: "node:${_NODE_VERSION}-buster-slim"
    dir: "web"
    entrypoint: "npm"
    args: ["run", "build"]
    env:
      - "NEXT_PUBLIC_GA_MEASUREMENT_ID=${_NEXT_PUBLIC_GA_MEASUREMENT_ID}"
      - "NEXT_PUBLIC_README_URL=${_NEXT_PUBLIC_README_URL}"
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    dir: "web"
    args:
      - gcloud
      - app
      - deploy
      - --project
      - $PROJECT_ID
      - --quiet
